export const SHOW_START = 'SHOW_START';
export const SHOW_SAVE_SUCCESS = 'SHOW_SAVE_SUCCESS';
export const SHOW_FAIL = 'SHOW_FAIL';
export const SHOW_SET_CURRENT = 'SHOW_SET_CURRENT';
export const SHOW_FETCH_ALL_DATA_SUCCESS = 'SHOW_FETCH_ALL_DATA_SUCCESS';
export const SHOW_UPDATE_ELEMENT = 'SHOW_UPDATE_ELEMENT';