
// showElements
export const SHOW_START = 'SHOW_START';
export const SHOW_SAVE_SUCCESS = 'SHOW_SAVE_SUCCESS';
export const SHOW_FAIL = 'SHOW_FAIL';
export const SHOW_SET_CURRENT = 'SHOW_SET_CURRENT';
export const SHOW_FETCH_ALL_DATA_SUCCESS = 'SHOW_FETCH_ALL_DATA_SUCCESS';
export const SHOW_UPDATE_ELEMENT = 'SHOW_UPDATE_ELEMENT';
export const SHOW_INCREMENT_CLOCK = 'SHOW_INCREMENT_CLOCK';
export const SHOW_INCREMENT_RUNNING_PART_DURATION = 'SHOW_INCREMENT_RUNNING_PART_DURATION';
export const SHOW_INITIATE_CLOCK = 'SHOW_INITIATE_CLOCK';
export const SHOW_TOGGLE_SHOW_SECONDS = 'SHOW_TOGGLE_SHOW_SECONDS';
export const SHOW_DECREMENT_PART_DURATION = 'SHOW_DECREMENT_PART_DURATION';
export const SHOW_SET_PAGE_TITLE = 'SHOW_SET_PAGE_TITLE';
export const SHOW_TOGGLE_DISPLAY_REALTIME = 'SHOW_TOGGLE_DISPLAY_REALTIME';
export const SHOW_SET_DISPLAY_USER = 'SHOW__SETDISPLAY_USER';
export const SHOW_TOGGLE_IS_EDITABLE = 'SHOW_TOGGLE_IS_EDITABLE';
export const SHOW_SET_OPTIONS_MENU_AND_ANCHOR = 'SHOW_SET_OPTIONS_MENU_AND_ANCHOR';
export const SHOW_CLEAR_DATA = 'SHOW_CLEAR_DATA';
export const SHOW_SET_SHOW_ALL_SCENES = 'SHOW_SET_SHOW_ALL_SCENES';



//live
export const LIVE_START = 'LIVE_START';
export const LIVE_FAIL = 'LIVE_FAIL';
export const LIVE_SET_IS_LIVE = 'LIVE_SET_IS_LIVE';
export const LIVE_TOGGLE_IS_PAUSED = 'LIVE_TOGGLE_IS_PAUSED';
export const LIVE_CHANGE_CURRENT_PART_NUMBER = 'LIVE_CHANGE_CURRENT_PART_NUMBER';
export const LIVE_RESET_RUNNING_PART_DURATION = 'LIVE_RESET_RUNNING_PART_DURATION';
export const LIVE_INCREMENT_RUNNING_PART_DURATION = 'LIVE_INCREMENT_RUNNING_PART_DURATION';
export const LIVE_END_PART = 'LIVE_END_PART';
export const LIVE_END_OF_SHOW = 'LIVE_END_OF_SHOW';
export const LIVE_UPDATE_SCHEDULED_END_TIME = 'LIVE_UPDATE_SCHEDULED_END_TIME';
export const LIVE_SAVE_PREVIOUS_STATE = 'LIVE_SAVE_PREVIOUS_STATE';
export const LIVE_SET_STATE = 'LIVE_SET_STATE';