
// showElements
export const SHOW_START = 'SHOW_START';
export const SHOW_FAIL = 'SHOW_FAIL';
export const SHOW_SET_CURRENT = 'SHOW_SET_CURRENT';
export const SHOW_FETCH_DATA_SUCCESS = 'SHOW_FETCH_DATA_SUCCESS';
export const SHOW_SUCCESS = 'SHOW_SUCCESS';
export const SHOW_CLEAR_DATA = 'SHOW_CLEAR_DATA';

//global
export const INCREMENT_CLOCK = 'INCREMENT_CLOCK';
export const INITIATE_CLOCK = 'INITIATE_CLOCK';
export const SHOW_SECONDS = 'SHOW_SECONDS';
export const SET_PAGE_TITLE = 'SET_PAGE_TITLE';
export const TOGGLE_DISPLAY_REALTIME = 'TOGGLE_DISPLAY_REALTIME';
export const DISPLAY_USER = 'SHOW__SETDISPLAY_USER';
export const TOGGLE_IS_EDITABLE = 'TOGGLE_IS_EDITABLE';
export const SET_OPTIONS_MENU_AND_ANCHOR = 'SET_OPTIONS_MENU_AND_ANCHOR';
export const SET_SHOW_ALL_SCENES = 'SET_SHOW_ALL_SCENES';

//live
export const LIVE_INCREMENT_RUNNING_PART_DURATION = 'LIVE_INCREMENT_RUNNING_PART_DURATION';
export const LIVE_UPDATE_SCHEDULED_END_TIME = 'LIVE_UPDATE_SCHEDULED_END_TIME';
export const LIVE_SET_STATE = 'LIVE_SET_STATE';
export const RESET_THE_SHOW = 'RESET_THE_SHOW';

